/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20__factory } from "./ERC20__factory";
export { GNSDiamond__factory } from "./GNSDiamond__factory";
export { Multicall3__factory } from "./Multicall3__factory";
